import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { AuditStore, buildGraph, type AiEvent } from "@ailogtrace/core";

export type ExportFormat = "md" | "json";

function aggregateRedactions(events: AiEvent[]): { ruleId: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const e of events) {
    for (const r of e.redactions) counts.set(r.ruleId, (counts.get(r.ruleId) ?? 0) + r.count);
  }
  return [...counts.entries()].map(([ruleId, count]) => ({ ruleId, count })).sort((a, b) => a.ruleId.localeCompare(b.ruleId));
}

export function renderMermaid(events: AiEvent[]): string {
  const g = buildGraph(events);
  const idToN = new Map(events.map((e, i) => [e.id, `N${i}`]));
  const lines: string[] = ["flowchart LR"];
  for (const e of events) {
    lines.push(`  ${idToN.get(e.id)!}["${e.seq}: ${e.kind}"]`);
  }
  for (const edge of g.edges) {
    lines.push(`  ${idToN.get(edge.from)!} -->|${edge.type}| ${idToN.get(edge.to)!}`);
  }
  return lines.join("\n");
}

export function renderMarkdown(store: AuditStore, sessionId: string): string {
  const events = store.getEvents(sessionId);
  const verify = store.verify();
  const redactions = aggregateRedactions(events);
  const totalRedactions = redactions.reduce((n, r) => n + r.count, 0);
  const span = events.length ? `${events[0].ts} → ${events[events.length - 1].ts}` : "(none)";

  const timeline = events.length
    ? ["| # | time | kind | redactions |", "|---|---|---|---|",
       ...events.map((e) => `| ${e.seq} | ${e.ts} | ${e.kind} | ${e.redactions.reduce((n, r) => n + r.count, 0)} |`)].join("\n")
    : "(no events)";

  const redactionTable = redactions.length
    ? ["| rule | count |", "|---|---|", ...redactions.map((r) => `| ${r.ruleId} | ${r.count} |`)].join("\n")
    : "No secrets were detected or redacted in this session.";

  return [
    `# AILogTrace Session Report — \`${sessionId}\``,
    "",
    "*Generated by AILogTrace v0.1.0 (walking skeleton). All events below are `observed` (deterministically captured); no inferred content is included in this build.*",
    "",
    "## Summary",
    "",
    `- **Session:** \`${sessionId}\``,
    `- **Events:** ${events.length}`,
    `- **Time span:** ${span}`,
    `- **Hash chain:** ${verify.ok ? "intact ✓ (tamper-evident)" : `BROKEN at rowid ${verify.brokenAtRowid} ✗`}`,
    `- **Redactions applied:** ${totalRedactions}`,
    "",
    "## Timeline",
    "",
    timeline,
    "",
    "## Workflow graph",
    "",
    "```mermaid",
    renderMermaid(events),
    "```",
    "",
    "## Redaction appendix",
    "",
    redactionTable,
    "",
    "## Methodology",
    "",
    "This report is generated from deterministically captured lifecycle events (Claude Code hooks). "
      + "Each event is stored append-only and hash-chained (`sha256(prevHash + canonical(event))`); "
      + "`ailogtrace verify` recomputes the chain. Secrets are redacted before persistence, so raw "
      + "secret values never reach the store — only redaction counts are recorded. Edges in the workflow "
      + "graph are sequential (`triggered`) in this skeleton; richer causal and inferred edges are a V1 concern.",
    "",
  ].join("\n");
}

export function renderJson(store: AuditStore, sessionId: string): { sessionId: string; events: AiEvent[]; graph: ReturnType<typeof buildGraph>; verify: ReturnType<AuditStore["verify"]> } {
  const events = store.getEvents(sessionId);
  return { sessionId, events, graph: buildGraph(events), verify: store.verify() };
}

export function exportSession(store: AuditStore, sessionId: string, format: ExportFormat, outDir: string): string {
  mkdirSync(outDir, { recursive: true });
  if (format === "json") {
    const file = join(outDir, `${sessionId}.json`);
    writeFileSync(file, JSON.stringify(renderJson(store, sessionId), null, 2));
    return file;
  }
  const file = join(outDir, `${sessionId}.md`);
  writeFileSync(file, renderMarkdown(store, sessionId));
  return file;
}
